name: Test Job for reusability 
on:
  workflow_dispatch:
jobs:
  my-job:
    # Importing a reusable workflow from another repository and branch
    uses: patilp76/actions-learning-pathway/.github/workflows/build-test-deploy.yml@main
    # Passing 'node-version' as an input parameter to the reusable workflow
    with:
      node-version: '18.x'
  hello-world-job:
    runs-on: ubuntu-latest
    needs: my-job
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
      - name: Generate list using Markdown
        run: |
              echo "## Following are the Details of the restore workflow" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
              echo "- database restored = ${DB_NAME}" >> $GITHUB_STEP_SUMMARY
              echo "- Pod in which database restored = ${POD_NAME}" >> $GITHUB_STEP_SUMMARY
              echo "- S3 Path Used = ${BACKUP_FILE_PATH}" >> $GITHUB_STEP_SUMMARY
