name: Test Job for reusability 
on:
  workflow_dispatch:
jobs:
  my-job:
    # Importing a reusable workflow from another repository and branch
    uses: patilp76/actions-learning-pathway/.github/workflows/build-test-deploy.yml@main
    # Passing 'node-version' as an input parameter to the reusable workflow
    with:
      node-version: '18.x'
  hello-world-job:
    runs-on: ubuntu-latest
    needs: my-job
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
      - name: Adding markdown
        run: echo ":white_check_mark:Successfully restored the \`${DB_NAME}\` to the :rocket:\`${POD_NAME}\` pod." >> $GITHUB_STEP_SUMMARY
